module.exports = ITEM_DISTRICT = {
    NORTHERN: "NORTHERN",
    NORTHEASTERN: 'NORTHEASTERN',
    NORTHWESTERN: "NORTHWESTERN",
    EASTERN: "EASTERN",
    CENTRAL: "CENTRAL",
    SOUTHWESTERN: "SOUTHWESTERN",
    SOUTHEASTERN: "SOUTHEASTERN",
    SOUTHERN: "SOUTHERN",
}